version: "3.9"

services:
  backend:
    image: ghcr.io/ndstt/refine-haus-clinic/backend:latest
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/ndstt/refine-haus-clinic/frontend:latest
    ports:
      - "5173:5173"
